name: vehicule-serveur
on:
  - push
  - pull_request
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: actions/setup-node@v4
        with: 
          node-version: 20.17
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint